# Generated by Django 3.1.6 on 2021-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0003_auto_20210209_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtree',
            name='depth',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
