# Generated by Django 3.1.6 on 2021-02-09 16:47

from django.db import migrations, models
from django.utils.text import slugify


def team_slug(apps, schema_editor):
    Team = apps.get_model("peoplefinder", "Team")

    for team in Team.objects.all():
        team.slug = slugify(team.name)
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0004_teamtree_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.RunPython(team_slug),
    ]
