# Generated by Django 3.1.6 on 2021-02-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0007_auto_20210210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='do_not_work_for_dit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
